apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: port-forward
  namespace: mongodb
rules:
  # Allow reading pods and services so kubectl can find the mongodb service/pod
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  # Allow the portforward subresource (this is the essential permission)
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create"]

  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]